name: Smoke tests Staging

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: "Deploy staging"

jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          record: true
          spec:
            - cypress/integration/candidate.spec.js
        env:
          CYPRESS_ENVIRONMENT: Staging
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_BASE_URL: https://staging.apply-for-teacher-training.education.gov.uk
          CYPRESS_CANDIDATE_TEST_EMAIL: ${{ secrets.CANDIDATE_TEST_EMAIL }}
          CYPRESS_GOVUK_NOTIFY_API_KEY: ${{ secrets.GOVUK_NOTIFY_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
