name: Smoke tests QA

on:
  pull_request: {}
  push:
    branches:
      - master
  repository_dispatch:
    types: "Deploy qa"

jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          record: true
          spec: cypress/integration/candidate.spec.js,cypress/integration/components.spec.js
        env:
          CYPRESS_ENVIRONMENT: QA
          CYPRESS_BASE_URL: https://qa.apply-for-teacher-training.service.gov.uk
          CYPRESS_CANDIDATE_TEST_EMAIL: ${{ secrets.CANDIDATE_TEST_EMAIL }}
          CYPRESS_GOVUK_NOTIFY_API_KEY: ${{ secrets.GOVUK_NOTIFY_API_KEY }}
      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: 'twd_apply_tech'
          SLACK_COLOR: '#c0392b'
          SLACK_ICON_EMOJI: ':sad-beaver:'
          SLACK_MESSAGE: 'Smoke tests failed to run :sadparrot:'
          SLACK_TITLE: 'Failure: ${{ github.workflow }}'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
