name: Smoke tests

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      environment:
        description: Apply Teacher Training environment to run smoke tests against qa, staging, sandbox or production
        required: true

jobs:
  set-matrix:
    runs-on: ubuntu-16.04
    outputs:
      environments: ${{ steps.select-environments.outputs.environments }}
    steps:
      - name: Select Environments
        id: select-environments
        run: |
          case $GITHUB_EVENT_NAME in
            push) environments='{"environment":["qa","staging","sandbox","production"]}' ;;
            workflow_dispatch) environments='{"environment":["${{ github.event.inputs.environment }}"]}' ;;
          esac
          echo "::set-output name=environments::$environments"

  cypress-run:
    runs-on: ubuntu-16.04
    needs: set-matrix
    strategy:
      matrix: ${{ fromJson(needs.set-matrix.outputs.environments) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set CYPRESS_BASE_URL
        run: |
          case ${{ matrix.environment }} in
            production) prefix=www ;;
            *) prefix=${{ matrix.environment }} ;;
          esac
          echo "CYPRESS_BASE_URL=https://${prefix}.apply-for-teacher-training.service.gov.uk" >> $GITHUB_ENV

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          record: true
          spec: cypress/integration/candidate.spec.js
        env:
          CYPRESS_ENVIRONMENT: ${{ matrix.environment }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_CANDIDATE_TEST_EMAIL: ${{ secrets.CANDIDATE_TEST_EMAIL }}
          CYPRESS_GOVUK_NOTIFY_API_KEY: ${{ secrets.GOVUK_NOTIFY_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: 'twd_apply_tech'
          SLACK_COLOR: '#c0392b'
          SLACK_ICON_EMOJI: ':sad-beaver:'
          SLACK_MESSAGE: 'Smoke tests failed to run :sadparrot:'
          SLACK_TITLE: 'Failure: ${{ github.workflow }} ${{ matrix.environment }}'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
